config/routes.rb
VivsanProject::Application.routes.draw do
  root :to => "users#sign_in"

  resources :gadgets

  resources :roles

  resources :users_admin

  resources :users do
    collection do
      get 'sign_up'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :firstname, :lastname, :email, :institution, :password, :role
	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\z/i
	validates_presence_of :firstname
	# validates_length_of :firstname, :within => 4..15
	validates_presence_of :lastname
	validates_presence_of :email
	validates_uniqueness_of :email
	validates_format_of :email, :with => EMAIL_REGEX
	validates_presence_of :password
	validates_length_of :password, :within => 5..15
	validates_confirmation_of :password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sign_in
    
  end

  def sign_up
    
  end

  def create
    @user = User.new(firstname: params[:user][:first_name],lastname: params[:user][:last_name], email: params[:user][:email], institution: params[:user][:institution], role: params[:user][:role], password: params[:user][:password])
    if @user.save
      redirect_to(:controller => 'users_admin', :action => 'index')
    else
        #puts "error messages"
        #puts @user.errors
        render(:controller => 'users', :action => 'sign_up')
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/sign_in.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-10 simple_form form-horizontal">
			<%= form_for :user, :url => users_admin_index_path, :method => 'get' do |user| %>
				<h1>Member Login</h1>
				<legend>
					<h4>If you are not a member yet please become a member 
					<%= link_to "here",sign_up_users_path %> to Sign In</h4>
				</legend>

				<% if flash[:error] %>
					<font color = "red" size = "4">
						<%= flash[:error].html_safe %>
					</font>	
				<% end %>

				<div class="form-group row">
  				 <%= user.label :Email, class: "string optional control-label control-label col-md-2 col-lg-2" %>
  				<div class="col-md-4 col-lg-4">	
  					<%= user.text_field :email, class: "form-control" %>
  				</div>
  			</div>

		    <div class="form-group row">
  				 <%= user.label :Password, class: "string optional control-label control-label col-md-2 col-lg-2" %>
  				<div class="col-md-4 col-lg-4">	
  					<%= user.password_field :password, class: "form-control" %>
  				</div>
  			</div>

  			<div class="form-group col-md-6 col-lg-6 row">
  				<%= user.submit "SignIn", class: "btn btn-primary", style: "margin-left: 20%"%>
  			</div>
			<%end%>
		</div>			
	</div>
</div>

app/views/users/sign_up.html.erb
	<div class="container">
  	<div class="row"> 
    	<div class="col-lg-10 ">	      	
      	<%= form_for :user, :url => users_path do |user|%>	
        	<h1>New Member Registration</h1>
        	<legend>
        		<h4>To get access to this inventory list of gadgets please fill out the following form. Thank you </h4>
        	</legend>
        	<!--<% if flash[:error] %>
						<font color = "red" size = "4">
							<%= flash[:error].html_safe %>
						</font>	
					<% end %>-->
					<%= error_messages_for(@user) %>
					<div class="form-group row">
						 <%= user.label :First_name, class: "string optional control-label control-label col-md-2 col-lg-2" %>
						<div class="col-md-4 col-lg-4">
							<%= user.text_field :firstname, class: "form-control" %>
						</div>
					</div>

				  <div class="form-group row">
				  	 <%= user.label :Last_name, class: "string optional control-label control-label col-md-2 col-lg-2" %>
				  	<div class="col-md-4 col-lg-4">		
				  		<%= user.text_field :lastname, class: "form-control" %>
				  	</div>
				  </div>

				  <div class="form-group row">
				  	 <%= user.label :Email, class: "string optional control-label control-label col-md-2 col-lg-2" %>
				  	<div class="col-md-4 col-lg-4">	
				  		<%= user.text_field :email, class: "form-control" %>
				  	</div>
				  </div>

				  <div class="form-group row">
				  	 <%= user.label :Institution, class: "string optional control-label control-label col-md-2 col-lg-2" %>
				  	<div class="col-md-4 col-lg-4">	
				  		<%= user.text_field :institution, class: "form-control" %>
				  	</div>
				  </div>

				  <div class="form-group row">
				  	 <%= user.label :Role, class: "string optional control-label control-label col-md-2 col-lg-2" %>
				  	<div class="col-md-4 col-lg-4">	
				  		<%= user.password_field :password, class: "form-control" %>
				  	</div>
				  </div>

				  <div class="form-group row">
				  	 <%= user.label :Confirm_password, class: "string optional control-label control-label col-md-2 col-lg-2" %>
				  	<div class="col-md-4 col-lg-4">	
				  		<%= user.password_field :confirmation, class: "form-control" %>
				  	</div>
				  </div>

				  <div class="form-group col-md-6 col-lg-6 row">
				  	<%= user.submit "Become a Member", class: "btn btn-primary", style: "margin-left: 20%"%>
				  </div>    	
    		<%end%>
    	</div>
  	</div>    
	</div>   