config/routes.rb
VivsanProject::Application.routes.draw do
  root :to => "users#sign_in"

  resources :gadgets

  resources :roles

  resources :users_admin

  resources :users do
    collection do
      get 'sign_up'
    end
  end

end

app/controllers/users_admin_controller.rb
class UsersAdminController < ApplicationController
	def index
		@users = User.all	
	end

	def new
		@user = User.new
	end

  def create
    # render :text => params.inspect and return
    @user = User.new(firstname: params[:user][:firstname],lastname: params[:user][:lastname], email: params[:user][:email], institution: params[:user][:institution], role: params[:user][:role], password: params[:user][:password])
    if @user.save
      flash[:notice] =  'User successfully created.' 
      redirect_to users_admin_index_path
    else
        flash[:error] =  'Problem creating user.' 
        render 'new'
    end
  end

	def show
		@user = User.find(params[:id])
    if !@user.nil?
      render 'show'
    else
      render 'index'
    end
	end

	def edit
    @user = User.find(params[:id])
    if !@user.nil?
      render 'edit'
    else
      render 'index'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.firstname = params[:user][:firstname]
    @user.lastname= params[:user][:lastname]
    @user.email= params[:user][:email]
    @user.institution= params[:user][:institution]
    @user.role= params[:user][:role]

    if @user.save  
      @users = User.all
      flash[:notice] =  'User successfully updated.'
      redirect_to users_admin_index_path
    else
      flash[:notice] =  'Problem updating user.'
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] =  'User successfully deleted.'
      redirect_to(:action => 'index')
    else
      flash[:notice] =  'Problem deleting user.'
      render 'index'
    end
  end
end

app/helpers/users_admin_helper.rb
module UsersAdminHelper
end

app/views/users_admin/_form.html.erb
<%= form_for :user, url: @url, method: @method, class: "form-horizontal" do |user| %>
	<%= error_messages_for(@user) %>
	<div class="form-group row">
    <%= user.label :First_name, class: "string optional control-label control-label col-md-2 col-lg-2" %>
  	<div class="col-md-4 col-lg-4">
  		<%= user.text_field :firstname, class: "form-control" %>
  	</div>
  </div>

  <div class="form-group row">
    <%= user.label :Last_name, class: "string optional control-label control-label col-md-2 col-lg-2" %>
  	<div class="col-md-4 col-lg-4">		
  		<%= user.text_field :lastname, class: "form-control" %>
  	</div>
  </div>

  <div class="form-group row">
    <%= user.label :Email, class: "string optional control-label control-label col-md-2 col-lg-2" %>
    <div class="col-md-4 col-lg-4">
  		<%= user.text_field :email, class: "form-control" %>
  	</div>
  </div>

  <div class="form-group row">
  	<%= user.label :Institution, class: "string optional control-label control-label col-md-2 col-lg-2" %>
  	<div class="col-md-4 col-lg-4">	
  		<%= user.text_field :institution, class: "form-control" %>
  	</div>
  </div>

  <div class="form-group row">
  	<%= user.label :Password, class: "string optional control-label control-label col-md-2 col-lg-2" %>
  	<div class="col-md-4 col-lg-4">	
  		<%= user.password_field :password, class: "form-control" %>
  	</div>
  </div>

  <div class="form-group row">
  	<%= user.label :Confirm_password, class: "string optional control-label control-label col-md-2 col-lg-2" %>
  	<div class="col-md-4 col-lg-4">	
  		<%= user.password_field :confirmation, class: "form-control" %>
  	</div>
  </div>

  <% @roles = Role.all%>
  <div class="form-group row">
  	<%= user.label :Role, class: "string optional control-label control-label col-md-2 col-lg-2" %>
  	<div class="col-md-4 col-lg-4">
     	<select class="form-control" name="user[role]">
        <%= @roles.each do |r|%>
   			<option value="<%= r.role%>"><%= r.role%></option>
   			<!-- <option value="User">User</option>
   			<option value="NRC Researcher">NRC Researcher</option> -->
        <% end %>
     	</select>
    </div>
  </div>
  <div class="form-group col-md-6 col-lg-6 row">
  	<%= link_to "Back", users_admin_index_path, class: "btn btn-primary", style: "margin-left: 10%"%>
  	<%= user.submit "Save", class: "btn btn-primary", style: "margin-left: 20%"%>
  </div>
<% end -%>

app/views/users_admin/edit.html.erb
<div class="container">
	<div class="row"> 
  	<div class="col-lg-10 ">	      	
      <% @url = users_admin_path %>
      <% @method = 'patch'%>
    	<%= render 'form'%>
  	</div>
	</div>    
</div>

app/views/users_admin/index.html.erb
<div class="row">
	<div class="col-md-10"> 
		<div class="row">											
			
		</div>
	</div>
	<div class="col-md-2 col-lg-2">
		<%= link_to("ADD USER",{:action => 'new'}, :class => 'btn btn-primary')%>
	</div>
	<div class="col-md-12">
		<center>
			<table class="table table-striped table-hover ">	
				<thead>
					<th>First Name</th>
					<th>Last Name</th>
					<th>email</th>
					<th>Institution</th>
					<th>Role</th>
					<th></th>
					<th></th>
					<th></th>
			  </th>
				
				<% @users.each do |user|%>
					<tr>
						<td><%= user.firstname%></td>
						<td><%= user.lastname%></td>
						<td><%= user.email%></td>
						<td><%= user.institution%></td>
						<td><%= user.role%></td>
						<td><%= link_to "view",users_admin_path(user.id)%></td>
						<td><%= link_to "edit",edit_users_admin_path(user.id)%></td>
						<td><%= link_to "delete",users_admin_path(user.id), :method => 'delete'%></td>
					</tr>
				<%end%>
			</table>
		</center>
	</div>
</div>

app/views/users_admin/new.html.erb
<div class="container">
	<div class="row"> 
  	<div class="col-lg-10 ">	      	
      <% @url = {controller: 'users_admin', action: 'create'} %>
      <% @method = 'post'%>
    	<%= render 'form'%>
  	</div>
	</div>   
</div>   

app/views/users_admin/show.html.erb
		<div class="container" style = "margin-top: 50px">
			<div class="well">
				<h1>
		  	The view of the user data...
				</h1>
				<div>
					<center>
						<table class="table table-striped table-hover">	
								<tr>
									<th>First Name :</th>
									<td><%= @user.firstname%></td>
								</tr>
								<tr>
									<th>Last Name :</th>
									<td><%= @user.lastname%></td>
								</tr>
								<tr>
									<th>email :</th>
									<td><%= @user.email%></td>
								</tr>
								<tr>
									<th>Institution :</th>
									<td><%= @user.institution%></td>
								</tr>
								<tr>
									<th>Role :</th>
									<td><%= @user.role%></td>
								</tr>
						</table>
					</center>
					<%= link_to("<<Back",{:controller => 'users_admin'}, :class => 'btn btn-primary')%>
					<%= link_to "Edit", edit_users_admin_path, class: 'btn btn-primary'%>
				</div>
			</div>
		</div>      