config/routes.rb
VivsanProject::Application.routes.draw do
  root :to => "users#sign_in"

  resources :gadgets

  resources :roles

  resources :users_admin

  resources :users do
    collection do
      get 'sign_up'
    end
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
	attr_accessible :role

	validates_presence_of :role
	validates_uniqueness_of :role
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def new
  end

  def index
  	@roles = Role.all
  end

  def create
  	@role = Role.new(role: params[:role][:role])
    
  	if @role.save
  		redirect_to roles_path
    else
        #puts "error messages"
        #puts @user.errors
        render 'new'
    end
  end

  def destroy
  	@role = Role.find(params[:id])
    if @role.destroy
      flash[:notice] = "Role successfully deleted."
      redirect_to roles_path
    else
      flash[:error] = "Problem occured while deleting the role"
      render 'index'
    end
  end

  def edit
  	@role = Role.find(params[:id])
    if !@role.nil?
      render 'edit'
    else
      render 'index'
    end
  end

  def update
  	@role = Role.find(params[:id])
    @role.role= params[:role][:role]

    if @role.save 
      flash[:notice] = "Role successfully updated."
    else
      flash[:error] = "Problem in updating the role."
    end
      @roles = Role.all
      render 'index'
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for :role, :url => @url, :method => @method do |role| %>
	<%= error_messages_for(@role) %>
	<div class="form-group row">
	 	<%= role.label :Role_name, class: "string optional control-label control-label col-md-2 col-lg-2" %>
 		<div class="col-md-4 col-lg-4">
			<%= role.text_field :role, class: "form-control"%>
		</div>
	</div>
	<div class="row col-lg-6 col-md-6">
		<%= link_to "Back", roles_path, :class => "btn btn-primary", style: "margin-left: 15%"%>
		<%= role.submit "Submit", :class => "btn btn-primary", style: "margin-left: 17%"%>
	</div>     	
<%end%>

app/views/roles/edit.html.erb
<div class="container">
 	<div class="well">
  	<div class="row"> 
    	<div class="col-lg-10 ">	      	
      	<% @url = role_path %>
      	<% @method = 'patch'%>
    		<%= render 'form'%>
    	</div>
  	</div>
 	</div>    
</div>   

app/views/roles/index.html.erb
<div class="row">
	<div class="col-md-8"> 
		<div class="row">
			<div class="col-lg=8 col-md=8"> 
			</div>											
			</br>
		</div>
	</div>
	<div class="col-md-2 col-lg-2">
		<%= link_to "ADD ROLE", new_role_path, :class => 'btn btn-primary'%>
	</div>
	<center>
		<table class="table table-striped table-hover ">	
			<th>
				<tr style = "background-color: #def">
				<td>Role</td>
				<td></td>
				<td></td>
				</tr>
		  </th>
			
			<% @roles.each do |role|%>
				<tr>
					<td><%= role.role%></td>
					<td><%= link_to "edit",edit_role_path(role.id)%></td>
					<td><%= link_to "delete",role_path(role.id), :method => 'delete'%></td>
				</tr>
			<%end%>
		</table>
	</center>
</div>

app/views/roles/new.html.erb
<div class="container">
	<div class="row"> 
  	<div class="col-lg-10 col-md-10">	      	
    	<% @url = {controller: 'roles', action: 'create'}%>
    	<% @method = 'post'%>
    	<%= render 'form'%>
  	</div>
	</div>  
</div>   