config/routes.rb
VivsanProject::Application.routes.draw do
  root :to => "users#sign_in"

  resources :gadgets

  resources :roles

  resources :users_admin

  resources :users do
    collection do
      get 'sign_up'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
	def error_messages_for(object)
		render(:partial => "application/error_messages", :locals => {:object => object})	
	end
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0%>
	<div id="errorExplanation">
		<h2><%= pluralize(object.errors.size, "error")%>prohibited this record from being saved</h2>
		<p>There were problems with the following fields:</p>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg%></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/application/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
	  <div class="nav navbar-header">
	    <a href="/devise/home/contact" class="navbar-brand">Contact</a>
	  </div>
	  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    <ul class="nav navbar-nav">
	      <li class="dropdown">
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown">English <b class="caret"></b></a>
	        <ul class="dropdown-menu">
	          <li><a href="#">German</a></li>
	          <li><a href="#">Spanish</a></li>
          	<li><a href="#">Hindi</a></li>
          	<li><a href="#">Chinese</a></li>
	        </ul>
	      </li>
	    </ul>
	    <ul class="nav navbar-nav pull-right">

	      <!--<li><a href="/users/sign_up">New member registration</a></li>      
	      <li><a href="/users/sign_in">LOGIN</a></li>-->
	      <li>
	      	<%= link_to("New member registration", sign_up_users_path) %>
	      </li>
	      <li>
	      	<%= link_to "LogIn",{:controller => 'users', :action => 'sign_in'} %>
	      </li>
	    </ul>
	  </div><!-- /.navbar-collapse -->
	</nav>

app/views/application/_navigation_backup.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  		<div class="nav navbar-header">
    		<a href="/devise/home/contact" class="navbar-brand">Contact</a>
  		</div>
  		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    		<ul class="nav navbar-nav">
      		<li class="dropdown">
        		<a href="#" class="dropdown-toggle" data-toggle="dropdown">English <b class="caret"></b></a>
        		<ul class="dropdown-menu">
          	<li><a href="#">German</a></li>
          	<li><a href="#">Spanish</a></li>
          	<li><a href="#">Hindi</a></li>
          	<li><a href="#">Chinese</a></li>
        		</ul>
      		</li>
    		</ul>
    		<ul class="nav navbar-nav pull-right">
      		<li>
      			<%= link_to("LogOut",{:controller => 'users', :action => 'sign_in'}, :class => 'action sign_in') %>
      		</li>
    		</ul>
  		</div><!-- /.navbar-collapse -->
		</nav>

app/views/application/_sidebar.html.erb
<div>
	<ul class="list-group">
		<li>
			<%= link_to "Users", users_admin_index_path, :class => "list-group-item active" %>
		</li>
		<li>
			<%= link_to "Roles", roles_path, :class => "list-group-item" %>
		</li>
		<li>
			<%= link_to "Gadgets", gadgets_path, :class => "list-group-item" %>
		</li>
	</ul>
</div>